name: ci

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build
        run: ./scripts/buildprod.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build and push Docker image
        run: gcloud builds submit --tag europe-central2-docker.pkg.dev/notely-457606/notely-ar-repo/notely:latest .

      - name: Migrate DB
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-central2-docker.pkg.dev/notely-457606/notely-ar-repo/notely:latest --region europe-central2 --allow-unauthenticated --project notely-457606 --max-instances=4